services:
  tcp-server:
    build:
      context: ../tcp
      dockerfile: Dockerfile
    image: redes-tcp:latest
    command: ["-mode=server", "-address=0.0.0.0", "-port=8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    
  udp-server:
    build:
      context: ../udp
      dockerfile: Dockerfile
    image: redes-udp:latest
    command: ["-mode=server", "-address=0.0.0.0", "-port=8080"]
    ports:
      - "8080:8080/udp"
    restart: unless-stopped
